/* ---------- mastery ---------- */
function mastery(){const tab=state.mTab;
  const tabs=[['path','Path to max'],['ladder','Rank ladder'],['sheet','Starter weapons (MR 0–12)'],['sframes','Easy Warframes'],['craft','Crafting chains'],['xp','XP farms']];
  let h=`<div class="stack"><div class="head"><div class="eyebrow">MR plan</div><h1>MR plan</h1><p class="lede">What to do next to reach your target rank, the full rank ladder, and the easiest gear to rank first. Enter what you've already ranked on the <a class="ln" href="#ranks">Ranks</a> page.</p></div>${bigMR()}<div class="seg" role="tablist">${tabs.map(([k,l])=>`<button class="btn ${tab===k?'on':''}" data-mtab="${k}" role="tab" aria-selected="${tab===k}">${l}</button>`).join('')}</div>`;
  if(tab==='sheet'){const by={};M.weapons.forEach(w=>(by[w.mr]=by[w.mr]||[]).push(w));
    h+=`<p class="small muted" style="margin:0">The cheapest weapons to rank, grouped by the Mastery Rank you need to build them. Together they give ${fmt(D.meta.sheetXp)} XP, enough to reach MR 12. "Path to max" carries on from there.</p>`+Object.keys(by).sort((a,b)=>a-b).map(mr=>`<details class="obj grp" data-scope="input.ck.mk" ${mr<=2?'open':''}><summary><h3>Mastery ${mr}</h3>${progHTML()}</summary>${by[mr].map(w=>mrow(w.id,w.slot)).join('')}</details>`).join('')}
  if(tab==='sframes')h+=`<details class="obj grp" data-scope="input.ck.mk" open><summary><h3>Easy Warframes</h3>${progHTML()}</summary>${M.frames.map(f=>mrow(f.id,f.src)).join('')}</details>
    <details class="obj grp" data-scope="input.ck.mk" open><summary><h3>Market companions</h3>${progHTML()}</summary>${M.companions.map(f=>mrow(f.id,'Market blueprint')).join('')}</details>`;
  if(tab==='craft'){const by={};M.craft.forEach(x=>(by[x.mr]=by[x.mr]||[]).push(x));
    h+=`<div class="callout small">Weapons used to craft other weapons. Rank the ingredient for its XP first, then build a spare copy for the recipe.</div>`+
    Object.keys(by).sort((a,b)=>a-b).map(mr=>`<details class="obj grp" data-scope="input.ck.mk" open><summary><h3>MR ${mr}</h3>${progHTML()}</summary>${by[mr].map(x=>`<div style="padding:10px 14px 0;border-top:1px solid var(--line)"><div class="mono small">${esc(x.recipe)} · ${fmt(x.xp)} XP</div>${x.note?`<div class="small" style="color:var(--warn)">${esc(x.note)}</div>`:''}</div>${x.targets.map(t=>mrow(t.id,'')).join('')}`).join('')}</details>`).join('')}
  if(tab==='xp')h+=`<div class="panel stack cut"><h2>Where to level gear fast</h2>
    <p class="small muted" style="margin:0">Best spots first. A frame that clears whole rooms ranks a fresh weapon to 30 in a few waves; stack an Affinity Booster on days you level several items.</p></div>
    <ol class="steps obj">${[['Hydron, Sedna (Defense)','Classic spot. Bring a frame that clears rooms (Saryn, Mesa, Gyre). Leave after wave 5–10.'],['Helene, Saturn (Defense)','Lower level than Hydron, good for new players. Also drops Orokin Cells.'],['Elite Sanctuary Onslaught','Best XP per minute once you have a strong frame. Talk to Cephalon Simaris in a Relay (needs The New Strange).'],['Steel Path Hydron / Helene','Same nodes on Steel Path give much more XP. Needs a strong build.'],['Affinity Booster + Sortie/Arbitration boosters','Boosters stack. Save them for a day you plan to level several items.'],['Star chart + Steel Path completion','The first clear of each node gives Mastery XP, and Steel Path pays it again. Track it under Missions.']].map(([a,b],i)=>step('xpfarm|'+i,a,b)).join('')}</ol>`;
  return h+'</div>'}
function ease(it){if(it.p)return it.v?(VAULT[it.n]&&VAULT[it.n].now?2:4):2;if(it.bc)return 0;if(it.bpd||it.dr)return 1;return 3}
const EASE=['Market blueprints','Boss and node drops','Farm relics','Quest, syndicate or vendor','Vaulted: buy on warframe.market'];
function mrow(id,note){if(!id)return'';const it=I[id];const k='m|'+id;const rk=P.rk[id];
  return `<div class="mitem${on(k)?' done':''}"><div class="top">${ck(k,'mk')}<details class="lazy" data-tree="${esc(id)}" data-note="${esc(note||'')}"><summary><span class="nm">${esc(id)}</span>${it&&it.mr?`<span class="chip">MR ${it.mr}</span>`:''}${rk&&!on(k)?`<span class="chip teal">R${rk}</span>`:''}<span class="chip">${fmt(mxp(it))} XP</span>${it&&it.p?priceChip(id+' Set'):''}<span class="open">Steps ▾</span>${note?`<span class="small muted" style="flex-basis:100%">${esc(note)}</span>`:''}</summary><div class="lazybody"></div></details></div></div>`}